####################################################################################################
# Copyright (c) 2016 - 2018, EPFL / Blue Brain Project
#               Marwan Abdellah <marwan.abdellah@epfl.ch>
#
# This file is part of NeuroMorphoVis <https://github.com/BlueBrain/NeuroMorphoVis>
#
# This library is free software; you can redistribute it and/or modify it under the terms of the
# GNU Lesser General Public License version 3.0 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with this library;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA.
####################################################################################################

__author__      = "Marwan Abdellah"
__copyright__   = "Copyright (c) 2016 - 2018, Blue Brain Project / EPFL"
__credits__     = ["Ahmet Bilgili", "Juan Hernando", "Stefan Eilemann"]
__version__     = "1.0.0"
__maintainer__  = "Marwan Abdellah"
__email__       = "marwan.abdellah@epfl.ch"
__status__      = "Production"


# System imports
import argparse

# Blender imports
from mathutils import Vector, Matrix
import neuron


####################################################################################################
# @parse_command_line_arguments
####################################################################################################
def parse_command_line_arguments(arguments=None):
    """Parses the input arguments.

    :param arguments:
        Command line arguments.
    :return:
        Arguments list.
    """

    # add all the options
    description = 'NeuroRender: a simple tool for rendering neurons generated by NeuroMorphoVis'
    parser = argparse.ArgumentParser(description=description)

    arg_help = 'Rendering configuration file'
    parser.add_argument('--config',
                        action='store', dest='config', help=arg_help)

    arg_help = 'Input directory, where the meshes are stored'
    parser.add_argument('--input-directory',
                        action='store', dest='input_directory', help=arg_help)

    arg_help = 'Input data type: blend, ply, obj'
    parser.add_argument('--input-type',
                        action='store', dest='input_type', help=arg_help)

    arg_help = 'Base image resolution'
    parser.add_argument('--resolution',
                        action='store', default=512, dest='resolution', help=arg_help)

    arg_help = 'Number of samples per pixel SPP'
    parser.add_argument('--spp',
                        action='store', default=32, dest='num_samples', help=arg_help)

    arg_help = 'Output directory, where the final image and scene will be stored'
    parser.add_argument('--output-directory',
                        action='store', dest='output_directory', help=arg_help)

    arg_help = 'Image and scene prefix'
    parser.add_argument('--prefix',
                        action='store', default='image', dest='prefix', help=arg_help)

    # Parse the arguments
    return parser.parse_args()


####################################################################################################
# @parse_rendering_configuration
####################################################################################################
def parse_rendering_configuration(configuration_file):
    """Parse a rendering configuration file.

    :param configuration_file:
        A given configuration file to load the neurons and rendering the scene.
    :return:
        A list of neurons.
    """

    # File contents
    config_data = list()

    # Read the configuration file
    config_file_handle = open(configuration_file, 'r')
    for line in config_file_handle:
        config_data.append(line)
    config_file_handle.close()

    # A list of all the parsed neurons
    neurons = list()

    # Parse the configuration
    index = 0
    while True:

        # We have reached the end of the file
        if index > len(config_data) - 1:
            break

        # Get a new line
        line = config_data[index]

        # If neuron is found
        if 'NEURON' in line:

            # Construct a new neuron object
            neuron_object = neuron.Neuron()

            # Parse neuron properties
            while True:

                # Get a new line
                index += 1
                line = config_data[index]

                # GID
                if 'GID' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('GID: ')
                    neuron_object.gid = line[1]
                elif 'TAG' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('TAG: ')
                    neuron_object.tag = int(line[1])
                elif 'MORPHOLOGY_TYPE' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('MORPHOLOGY_TYPE: ')
                    neuron_object.mtype = line[1]
                elif 'MORPHOLOGY_LABEL' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('MORPHOLOGY_LABEL: ')
                    neuron_object.mlabel = line[1]
                elif 'POSITION' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('POSITION: ')[1]
                    line = line.split(' ')
                    x = float(line[0])
                    y = float(line[1])
                    z = float(line[2])
                    neuron_object.position = Vector((x, y, z))
                elif 'ORIENTATION' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('ORIENTATION: ')
                    neuron_object.orientation = float(line[1])
                elif 'COLUMN' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('COLUMN: ')
                    neuron_object.column = line[1]
                elif 'LAYER' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('LAYER: ')
                    neuron_object.layer = line[1]
                elif 'TRANSFORM' in line:
                    line = line.replace('    ', '')
                    line = line.replace('\n', '')
                    line = line.split('TRANSFORM: ')[1]
                    line = line.split(' ')
                    t = Matrix()
                    t[0][0:4] = float(line[0]), float(line[1]), float(line[2]), float(line[3])
                    t[1][0:4] = float(line[4]), float(line[5]), float(line[6]), float(line[7])
                    t[2][0:4] = float(line[8]), float(line[9]), float(line[10]), float(line[11])
                    t[3][0:4] = float(line[12]), float(line[13]), float(line[14]), float(line[15])
                    neuron_object.transform = t
                elif not line.strip():
                    # Neuron is done
                    break
                else:
                    # Unrecognized parameter
                    continue

            # Add the neurons to the list
            neurons.append(neuron_object)

            # Increment the index
            index += 1

    return neurons
